#!/bin/bash

if [[ $# -ne 3 ]] ;then
    echo "usage: ii num1 num2 num3"
    exit 1
fi

max_num="$1"

if [[ "$max_num" -lt "$2" ]] ;then
    max_num="$2"
fi

if [[ "$max_num" -lt "$3" ]] ;then
    max_num="$3"
fi

echo "$max_num"
